import { Component, OnInit, VERSION } from '@angular/core';
import {
  GetContextMenuItemsParams,
  GridOptions,
  MenuItemDef,
  _,
} from 'ag-grid-community';
import { InputCellRendererComponent } from './input-cell-renderer/input-cell-renderer.component';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  name = 'Angular ' + VERSION.major;
  columnDefs: any;
  rowData: Object[] = [];
  gridOptions;

  constructor() {}
  ngOnInit(): void {
    this.initGrid();
    this.gridOptions = <GridOptions>{
      getContextMenuItems: this.getContextMenuItems,
      suppressPaginationPanel: true,
      rowHeight: 35,
      rowSelection: 'multiple',
      multiSortKey: 'ctrl',
      rowBuffer: 50,

      defaultColDef: {
        editable: false,
        sortable: true,
        filter: true,
        resizable: true,
        suppressKeyboardEvent: function (params) {
          return true;
        },
        suppressRowClickSelection: true,
        rowMultiSelectWithClick: true,
      },
    };
    setTimeout(() => {
      this.gridOptions.context = {
        thisComponent: this,
      };
    }, 10);
  }
  initGrid() {
    this.columnDefs = [
      {
        headerName: '',
        width: 35,
        checkboxSelection: true,
        suppressColumnsToolPanel: true,
        resizable: false,
        headerCheckboxSelection: true,
        headerCheckboxSelectionFilteredOnly: true,
        suppressMovable: true,
        suppressMenu: true,
        filter: false,
        pinned: 'left',
        sortable: false,
        cellStyle: { 'padding-top': '6px' },
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
      {
        headerName: 'Quantity',
        width: 180,
        field: 'Quantity',
        cellRenderer: InputCellRendererComponent,
        valueGetter: '20',
        cellClass: 'decimalType',
      },
    ];
  }
  onGridReady($event) {
    this.rowData = this.addAdditionalRows([{ Quantity: 50 }]);
  }
  addAdditionalRows(dataItems: Array<any>): any[] {
    for (let i = 0; i < 800; i++) {
      let row = _.cloneObject(dataItems[0]);
      row.itemNo = i + 3;
      row.rootItemNo = i + 3;
      row.cmirPriorityIndicator = true;
      dataItems.push(row);
    }
    return dataItems;
  }
  getContextMenuItems(params) {
    console.log('getContextMenuItems');
    var result: (string | MenuItemDef)[] = [
      {
        // custom item

        name: 'Copy To Group ',
        action: () => {
          window.alert('Alerting about ' + params.value);
        },
      },

      'copy',
      'separator',
      'chartRange',
    ];
    return result;
  }
}
